// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIjb7HfD-V9ZhZA5_wSy0uZ0dJe3UdmzE',
    appId: '1:957935772440:web:e40f654c24c1983dc8f46d',
    messagingSenderId: '957935772440',
    projectId: 'journalapp-396af',
    authDomain: 'journalapp-396af.firebaseapp.com',
    storageBucket: 'journalapp-396af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNVzF72wNfOtcz6GyHGt3HkH-mUpdK9Ww',
    appId: '1:957935772440:android:290563a44dfca55ec8f46d',
    messagingSenderId: '957935772440',
    projectId: 'journalapp-396af',
    storageBucket: 'journalapp-396af.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqn5_4VvN7tCkNHXsD2AAGyHxd-OWQY60',
    appId: '1:957935772440:ios:e8a51bda2d45dbedc8f46d',
    messagingSenderId: '957935772440',
    projectId: 'journalapp-396af',
    storageBucket: 'journalapp-396af.firebasestorage.app',
    iosBundleId: 'com.example.journalapp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqn5_4VvN7tCkNHXsD2AAGyHxd-OWQY60',
    appId: '1:957935772440:ios:e8a51bda2d45dbedc8f46d',
    messagingSenderId: '957935772440',
    projectId: 'journalapp-396af',
    storageBucket: 'journalapp-396af.firebasestorage.app',
    iosBundleId: 'com.example.journalapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIjb7HfD-V9ZhZA5_wSy0uZ0dJe3UdmzE',
    appId: '1:957935772440:web:0b722bc208b33eeac8f46d',
    messagingSenderId: '957935772440',
    projectId: 'journalapp-396af',
    authDomain: 'journalapp-396af.firebaseapp.com',
    storageBucket: 'journalapp-396af.firebasestorage.app',
  );
}
